app:
  name: angular-spring-jwt

jwt:
  header: Authorization
  expires_in: 60000 # 10 minutes
  secret: queenvictoria
  cookie: AUTH-TOKEN

logging:
  level:
    org.springframework.web: ERROR
    com.bfwg: DEBUG

#hibernate:
#  dialect: PostgreSQLDialect

#spring:
#  jpa:
#    database: POSTGRESQL
#    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
#    show-sql: true
#    generate-ddl: true
#    hibernate:
#      ddl-auto: create-drop
#    properties:
#      hibernate:
#        jdbc:
#          lob:
#            non_contextual_creation: true
#      temp:
#        use_jdbc_metadata_defaults: false
#  datasource:
#    platform: postgres
#    url: "jdbc:postgresql://localhost:5432/WhereIsMyMoney_v1"
#    username: postgres
#    password: admin
#    driver-class-name: org.postgresql.ds.PGSimpleDataSource
#
#spring:
#  jpa:
#    hibernate:
#      ddl-auto: create
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  datasource:
#    url: "jdbc:postgresql://localhost:5432/WhereIsMyMoney_v1"
#    username: postgres
#    password: admin
#    driver-class-name: org.postgresql.ds.PGSimpleDataSource

#spring:
#  jpa:
#    hibernate:
#      # possible values: validate | update | create | create-drop
#      ddl-auto: create-drop
#  datasource:
#    url: jdbc:mysql://localhost/myDatabase
#    username: myUser
#    password: myPassword
#    driver-class-name: com.mysql.jdbc.Driver


spring:
  jpa:
    show-sql: true
  #  jpa:
#    hibernate:
      # possible values: validate | update | create | create-drop
#      ddl-auto: create-drop
#      ddl-auto: update
  datasource:
    url: "jdbc:postgresql://localhost:5432/WhereIsMyMoney_v1"
    username: postgres
    password: admin
#    driver-class-name: org.postgresql.ds.PGSimpleDataSource
    data-source-class-name: org.postgresql.ds.PGSimpleDataSource
