app:
  name: angular-spring-jwt

jwt:
  header: Authorization
  expires_in: 60000 # 10 minutes
  secret: queenvictoria
  cookie: AUTH-TOKEN

logging:
  level:
    org.springframework.web: ERROR
    com.bfwg: DEBUG



file:
  upload:
#    location: "/Users/uploads"
    location: "/Users/motos/IdeaProjects/angular-spring-starter/server/src/main/resources/pdfs/"

spring:
  servlet:
    multipart:
      max-request-size: 215MB
      max-file-size: 200MB
      file-size-threshold: 2KB
      enabled: true
  jpa:
    show-sql: true
  datasource:
    url: "jdbc:postgresql://localhost:5432/WhereIsMyMoney_v1"
    username: postgres
    password: admin
    data-source-class-name: org.postgresql.ds.PGSimpleDataSource
